### ISSUE TITLE
[BUG] The `$ref` keyword is ignored in some cases

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#1167]
**Describe the bug**
In schemas with deep reference nesting, the `$ref` keyword may be ignored while transforming the Open API parameter to JSON Schema.

**To Reproduce**
1. Run schemathesis against the schema below
2. Observe non-strings generated for `case.query["key"]`

If possible, please post a minimal version of your API schema that cause this behavior:

```yaml
{
        "openapi": "3.0.2",
        "info": {"title": "Test", "description": "Test", "version": "0.1.0"},
        "paths": {
            "/data": {
                "get": {
                    "parameters": [
                        {
                            "name": "key",
                            "in": "query",
                            "required": True,
                            "schema": {"$ref": "#/components/schemas/foo1"},
                        }
                    ],
                    "responses": {"200": {"description": "OK"}},
                }
            }
        },
        "components": {
            "schemas": {
                "foo1": {"$ref": "#/components/schemas/foo2"},
                "foo2": {"$ref": "#/components/schemas/foo3"},
                "foo3": {"$ref": "#/components/schemas/foo4"},
                "foo4": {"$ref": "#/components/schemas/foo5"},
                "foo5": {"$ref": "#/components/schemas/foo6"},
                "foo6": {"$ref": "#/components/schemas/bar"},
                "bar": {"type": "string"},
            }
        },
    }
```

**Expected behavior**
All values for `case.query["key"]` should be strings
