### ISSUE TITLE
[BUG] Explicit examples for Open API query parameters do not use the defined "style"

### ISSUE THREAD

**Issue by m-develops** [schemathesis/schemathesis#1190]
**Describe the bug**
With the component below the query params are not rendered correctly.
The example below gives the uri: uri: 'http://localhost/api/product/v1/products?page=number&page=size'

**To Reproduce**
1. Make a GET path with the component below in the parameter
2. Run the schemathesis CLI command

If possible, please post a minimal version of your API schema that cause this behavior:

```yaml
components:
  parameters:
    page:
      in: query
      name: page
      description: Page number
      required: false
      style: deepObject
      explode: true
      schema:
        type: object
        additionalProperties: false
        properties:
          number:
            type: integer
            minimum: 1
            maximum: 100
            example: 1
          size:
            type: integer
            minimum: 1
            maximum: 100
            example: 15
```

**Expected behavior**
I would expect an uri like:  'http://localhost/api/product/v1/products?page[number]=1&page[size]=15'

**Additional context**
It looks like this worked in the past:
https://github.com/schemathesis/schemathesis/issues/599
