### ISSUE TITLE
[BUG] regex patterns giving invalid values

### ISSUE THREAD

**Issue by hoog1511** [schemathesis/schemathesis#1350]
**Checklist**

- [ ] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
My regex patterns tend to generate a lot of values which exceed the maximumLength I provide inside the regex itself. I get a lot of values which end with "\n" for some reason. When I provide a similar pattern for a header it has a lot less deviations from the pattern.

```yaml
{
   administrationCode {
      pattern: '^[0-9]{2,4}$'
      type: string
      example: "1201"
      description: Administration Code of the product.
}
```

**Expected behavior:**
administrationCode : 1234

**Environment:**
 - OS: [Windows]
 - Python version: [3.10.0]
 - Schemathesis version: [stable]
 - Spec version: [Open API 3.0.3]
