### ISSUE TITLE
[BUG] Multiple Examples do not work in explicit mode

### ISSUE THREAD

**Issue by TradingMarius** [schemathesis/schemathesis#1360]
**Checklist**

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**
When I run schemathesis with the `explicit` flag,
schemathesis does not only run the provided examples, but also additional requests where the parameter that uses the `examples` keyword is set to `0`. This only happens when I have multiple parameters defined and I am using the `examples` key instead of the `example` key.

**To Reproduce**
1. Run this command
```
 schemathesis run --base-url http://localhost:8080  --checks all --hypothesis-phases=explicit  openapi.yml
```
2. See error
```1. Received a response with a status code, which is not defined in the schema: 404

Declared status codes: 200

Path parameters : {'param1': '0'}
Headers         : {'User-Agent': 'schemathesis/3.11.5', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}
Query           : {'api_version': 23}

----------

Response payload: `<html>
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
  The resource could not be found.<br/><br/>
```

If possible, please post a minimal version of your API schema that cause this behavior:

```yaml
get:
  parameters:
    -in: path
      name: param1
      schema:
        type: string
      examples:
        one:
          value: string1
        two:
          value: string2
      required: true
   - in: query
      name: api_version
      schema:
        type: integer
      required: false
      example: 23
```

**Expected behavior**
I expect schemathesis to execute these 4 requests:
```
param1: string1, api_version: 23
param1: string2, api_version: 23
param1: string1, api_version: None
param1: string2, api_version: Nine
```
but it also executes:
```
param1: 0, api_version: 23
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Python version: 3.8.12
 - Schemathesis version: 3.11.5
 - Spec version: Open API 3.0.2

**Additional context**

**Comment by Stranger6667** [comment]
Hi!

Thank you for a detailed report! This behavior is likely caused by the fact that Hypothesis re-tries failed examples multiple times even on the `explicit` phase. I almost finished a FAQ entry on this matter a few weeks ago, but it is still not there. There is an open issue to implement a way to disable this behavior - #1081

On the Schemathesis side, we generate some feasible number of combinations (to avoid a combinatorial blowup), so there are some upper bounds as well.

There is also #1065 to overhaul the current approach - but the approach described there is probabilistic, so no guarantees that all examples are always checked.

**Comment by TradingMarius** [comment]
Thanks again for your quick reply! :)
I am not sure if this is caused by retrying failed examples.

I registered a `before_add_examples` hook 
```python
@schemathesis.hooks.register
def before_add_examples(
    context: schemathesis.hooks.HookContext,
    examples: List[Case],
) -> None:
    print(examples)
```
now that just prints the examples:


```python
[Case(path_parameters={'param1': 'string1'}, query={}), Case(path_parameters={'param1': 'string2'}, query={}), Case(path_parameters={'param1': '0'}, query={'api_version': 23})]
```
We already have the example where `param1` is set to `0` in there.

What is weird is, that it does not generate any examples with a valid `param1` and the `api_version` set somehow.

Maybe I can filter out the that additional example in the `before_add_Examples` hook?

**Comment by Stranger6667** [comment]
> We already have the example where param1 is set to 0 in there.
> What is weird is, that it does not generate any examples with a valid param1 and the api_version set somehow.

Hm, it looks like the examples "merging" logic doesn't do it properly, as if there are two params with examples, it should contain a combination with both of them.

> Maybe I can filter out the that additional example in the before_add_Examples hook?

Yep, the main thing to do inside `before_add_examples` is to modify `examples` in place by adding new ones or removing/modifying existing ones

**Comment by TradingMarius** [comment]
Thanks again! I will try to do that.
BTW I love schemathesis. It fits perfectly to our use case!

**Comment by Stranger6667** [comment]
Happy to help! :)

> BTW I love schemathesis. It fits perfectly for our use case!

Great to hear that :) As I am planning new features and want to improve current workflows, I'd be happy to learn more about your use case - so, if you could share it with me (here/gitter chat/email), it would be awesome! :)

**Comment by petkostas** [comment]
I might be experiencing the same issue, though I am not getting a detailed report (should I open another ticket for this?), just `Hypothesis found 3 failures in explicit examples.` (bellow it's a modified output of the test)

```
    @test_api.parametrize(
>       endpoint=[
            "^/api/v2/test/{some_var}/test$",
        ]
    )
    @test_api.given(data=st.data())
    @settings(max_examples=50)
    def test_some_api(data, case):
E   hypothesis.errors.MultipleFailures: Hypothesis found 3 failures in explicit examples.
```

**Comment by TradingMarius** [comment]
I found somewhat of a quick fix for my problem. I changed the second parameter to use the `examples` keyword instead of `example`. It looks like this now:
```yaml
get:
  parameters:
    -in: path
      name: param1
      schema:
        type: string
      examples:
        one:
          value: string1
        two:
          value: string2
      required: true
   - in: query
      name: api_version
      schema:
        type: integer
      required: false
      examples:
        abc:
          value: 23
```

This produces a better outcome for us:
```python
[Case(path_parameters={'param1': 'string1'}, query={'api_version': 23}), Case(path_parameters={'param1': 'string2'}, query={'api_version': 23})]
```

This is not excactly what it should be, but works better. It does not work when using more than 1 example for the `api_version` though.

I can share a little bit regarding our use case in private. :)
