### ISSUE TITLE
[BUG] API returns error that is not marked as a failed test

### ISSUE THREAD

**Issue by marcosanchotene** [schemathesis/schemathesis#1368]
**Checklist**

- [ X ] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [ X ] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Bug description**
A request sent without a required field that is not correctly configured as required in the OpenAPI specification returns an error that is not detected.

**To Reproduce**
1. Write a test in Python like below:
```
import logging

import schemathesis
from hypothesis import settings

logger = logging.getLogger('schema_testing')
schema = schemathesis.from_path("openapi.yaml", base_url=<URL>)


@schema.parametrize()
@settings(max_examples=500, deadline=60000)
def test_api(case):
    logger.info(f'Request -> body: {case.body} - path: {case.path}')
    response = case.call(auth=(<user>, <password>), timeout=60000)
    logger.info(f'Response -> {response.text}')
    case.validate_response(response)
```
2. Execute the test with pytest.
3. The test passes.
4. Check the log.
5. The log shows some tests were made without the required property, which returned a 400 bad request response. These tests were not detected as failures.

Minimal version of the API schema that causes this behavior:

```yaml
{
    "openapi": "3.0.3"
    Request:
      type: object
      required:
        - property1
      properties:

        property1:
          description: Description 1.
          example: https://example.com/item-page
          type: string
        property2:
          description: Description 2.
          type: boolean
          default: false
}
```

**Expected behavior**
A test made with a valid `property1` and without `property2` that returns a 400 response should fail as the only required property is `property1`. According to the specification, a test sent only with a valid `property1` should return a 200 response, which was not the case.

**Environment:**
 - OS: Linux
 - Python version: 3.7.12
 - Schemathesis version: 3.11.5
 - Spec version: Open API 3.0.3

**Additional context**
As described above, `property2` should be required in the API specification, but is not. It is a known issue that will be fixed later. However, I would expect Schemathesis to report that issue. Apparently it is just checking whether the status code of the response is on the list of expected responses on the specification.
