### ISSUE TITLE
[FEATURE] documentation about running schemathesis in Gitlab-CI

### ISSUE THREAD

**Issue by arthurzenika** [schemathesis/schemathesis#1468]
**Is your feature request related to a problem? Please describe.**

We're running schemathesis in gitlab CI against an environment built and deployed with AutoDevops. 

It would be nice to have a small snippet one could copy/paste from the documentation to get started with schemathesis on a CI system. 

Here is how we got it working : 

```
schemathesis_tests:
    stage: performance
    image: 
        name: schemathesis/schemathesis:stable
        entrypoint: [""]
    script:
        - CI_ENVIRONMENT_URL="$(cat environment_url.txt)"
        - export CI_ENVIRONMENT_URL
        - schemathesis run --checks all docs/swagger.json --base-url $CI_ENVIRONMENT_URL
```

**Describe the solution you'd like**
Maybe have something simpler which doesn't involve the `environment_url.txt` based URL. 

Anyway, kudos for a nice tool ! We're hoping to use it more on our project.
