### ISSUE TITLE
[FEATURE] Open API: named auth implementation

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#1710]
### Problem

It could be tedious to use different auth types within the same Open API schemas in Schemathesis. Essentially it means duplicating the filtering logic inside the auth implementation itself (filters will simplify it though).

### Solution

Add a method that makes Schemathesis use certain auth mechanisms based on their name & type.

Schema:

```yaml
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    OpenID:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
    OAuth2:
      type: oauth2
      flows:
        password:
          refreshUrl: https://example.com/oauth/refresh
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations
```

Then it could be something like:

```python
schema.auth.openapi.http_basic("BasicAuth", username="username", password="password")
schema.auth.openapi.http_bearer("BearerAuth", token="TOKEN")
schema.auth.openapi.api_key("ApiKeyAuth", api_key="API-KEY")
```

I.e. some specifically typed methods that will automatically add proper impl under the hood.

Alternative, a simpler interface, but typing would be harder to specify (+ some validation would be needed):

```python
schema.auth.openapi.define("BasicAuth", username="username", password="password")
schema.auth.openapi.define("BearerAuth", token="TOKEN")
schema.auth.openapi.define("ApiKeyAuth", api_key="API-KEY")
schema.auth.openapi.define("OAuth2", username="username", password="password")
```

Also, overriding some values would be nice for testing purposes - e.g. specify a different `refreshUrl` for testing purposes.

Probably Schemathesis can't support all security schemes, especially ones with device auth codes, but username / password or token-like should be a good starting point.

### Implementation notes

- I'd like to have everything called via `schema.auth`, but since `AuthStorage` is spec-agnostic we might need to subclass it in order to add some setup-time validation for inputs
