### ISSUE TITLE
[BUG] Unable to pass "Authorization: Bearer AUTH_TOKEN" header correctly in Github Action Yaml file

### ISSUE THREAD

**Issue by AryanGodara** [schemathesis/schemathesis#1764]
**Checklist**

- [X] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [X] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)

**Describe the bug**

**To Reproduce**
Run the github action script `st.yaml` below by appending the following data to it :-

(  I've given 4 different approaches to adding the header as an argument; but none of them parse the auth token correctly.
If there is more than one whitespace, eg.: `"Authorization: Bearer $ACCESS_TOKEN"`, the string gets truncated to `"Authorization: Bearer"` )
( Another example is passing `"Authorization: $ACCESS_TOKEN"` works just fine)

```yaml
- name: Run st for bootstrap.yml
        if: always()
        uses: schemathesis/action@v1
        with:
          schema: './api/openapi/bootstrap.yml'
          base-url: 'http://localhost'
          args: "-H Authorization: Bearer {{ env.ACCESS_TOKEN }}"
          token: ${{ secrets.SCHEMATHESIS_TOKEN }}

      - name: Run st for bootstrap.yml
        if: always()
        uses: schemathesis/action@v1
        with:
          schema: './api/openapi/bootstrap.yml'
          base-url: 'http://localhost'
          args: -H Authorization:Bearer ${{ env.ACCESS_TOKEN }}
          token: ${{ secrets.SCHEMATHESIS_TOKEN }}

      - name: Run st for bootstrap.yml
        if: always()
        uses: schemathesis/action@v1
        with:
          schema: './api/openapi/bootstrap.yml'
          base-url: 'http://localhost'
          args: -H Authorization:${{ env.BEARER_TOKEN }}
          token: ${{ secrets.SCHEMATHESIS_TOKEN }}

      - name: Run st for bootstrap.yml
        if: always()
        uses: schemathesis/action@v1
        with:
          schema: './api/openapi/bootstrap.yml'
          base-url: 'http://localhost'
          args: "-H 'Authorization: Bearer ${{ env.ACCESS_TOKEN }}'"
          token: ${{ secrets.SCHEMATHESIS_TOKEN }}
```

1. Run this command '...'
2. See error

If possible, please post a minimal version of your API schema that cause this behavior:

st.yaml :-
```yaml
{
name: Test OpenAPI using Schemathesis

on: [push, pull_request] 

env:
  MF_TOKEN: abcd
  EMAIL: admin@example.com
  PASSWORD: 12345678
  DEVICE: mf-device

jobs:
  api-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: find number of cores
        run: lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'

      - name: create images
        if: always()
        run: make all -j 2 && make -j 2 dockers_dev

      - name: run containers
        if: always()
        run: make run ARGS="-d"

      - name: REST API with curl to provision user
        if: always()
        run: |
          curl -sSiX POST http://localhost:9002/users -H "Content-Type: application/json" -d '{"name": "John Doe","credentials": {"identity": "admin@example.com","secret": "12345678"}}'
      
      - name: Set ACCESS_TOKEN
        id: set-access-token
        run: |
          response='{"access_token":"..." ... }' # Replace with your JSON response
          access_token=$(echo "$response" | grep -o '"access_token":"[^"]*' | cut -d'"' -f4)
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Set BEARER_TOKEN
        run: echo "BEARER_TOKEN=Bearer $MF_TOKEN" >> $GITHUB_ENV

      - name: Run the tests for bootstrap.yml
        run: .... (Written above)
}
```

**Expected behavior**
I want the "Authorization: Bearer ACCESS_TOKEN" to be used correctly inside the github action, just as it is inside the st CLI.

**Environment (please complete the following information):**

- OS: [Linux: Ubuntu 22.04 LTS ]
- Python version: [3.10.2]
- Schemathesis version: [3.19.6]
- Spec version: [Open API 3.0.1]

**Additional Context**

I'm using this inside a pull request for Mainflux IoT Platform 
Link to the Pull Request: `https://github.com/mainflux/mainflux/pull/1692`

**Comment by Stranger6667** [comment]
I’ll be able to check it in details this Sunday at earliest. Thank you for reporting such an issue, it really helps me to improve the tool

**Comment by AryanGodara** [comment]
> I’ll be able to check it in details this Sunday at earliest. Thank you for reporting such an issue, it really helps me to improve the tool

Just one question, if instead of github action; I install schemathesis on github workflow, and directly run the cli commands in subsequent jobs; will I be able to get a pass fail check, or will it simply print the output ?
(In clear words: Can I replace using default `schemathesis github action` with using the `st CLI` inside a github_action.yaml file)

And again, thanks for the response @Stranger6667 !!

**Comment by Stranger6667** [comment]
Hi @AryanGodara !

It turned out that this version works (I took this example from the [Schemathesis Action repo](https://github.com/schemathesis/action)):

```yaml
# Extract the access token from 'secret.json' and save it to $GITHUB_ENV as ACCESS_TOKEN.
- name: Set access token
  run: cat apps/python/secret.json | python3 -c "import sys, json; print(f'ACCESS_TOKEN={json.load(sys.stdin)[\"access_token\"]}')" >> $GITHUB_ENV

# Use the saved access token in the Schemathesis GitHub action.
- uses: schemathesis/action@v1
  with:
    schema: 'https://example.schemathesis.io/openapi.json'
    args: '-H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}"'
```

I.e. it looks like the header value should be enclosed in quotes. I updated the docs in this repo and in the action repo with this example and a few extra notes - hopefully, it is a bit more clear now in this regard.

As for your question:

> Just one question, if instead of github action; I install schemathesis on github workflow, and directly run the cli commands in subsequent jobs; will I be able to get a pass fail check, or will it simply print the output ?
(In clear words: Can I replace using default schemathesis github action with using the st CLI inside a github_action.yaml file)

Yes, you can! The GitHub Action we have just installs Schemathesis CLI and [passes all the configured options](https://github.com/schemathesis/action/blob/main/action.yml#L62) to it:

```yaml
    - run: |
        source env/bin/activate
        schemathesis run \
          ${{ inputs.schema }} \
          --hypothesis-database=:memory: \
          --hypothesis-max-examples=${{ inputs.max-examples }} \
          --checks=${{ inputs.checks }} \
          ${{ inputs.args }} \
```

As far as I know, GitHub Actions use the exit code of a command to decide whether a step failed or not - Schemathesis CLI adheres to this convention, so you may expect it to work as any other tool in this regard.

Let me know if there are any aspects you'd like me to clarify
