### ISSUE TITLE
[BUG] date-times now fail validation upgrading from 3.33.x to 3.35.x

### ISSUE THREAD

**Issue by dashdanw** [schemathesis/schemathesis#2481]
### Checklist

- [ ] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [ ] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [ ] I am using the latest version of Schemathesis

### Describe the bug

Date times formatted with `str(some_datetime)` e.g `2018-03-26 14:43:59.004000+00:001` are missing the `T` annotation, which used to pass validation. These now fail checks for date-time formatted fields, ie. 
```
E           Schema at /properties/user/properties/date_joined:
E       
E               {
E                   "type": "string",
E                   "format": "date-time",
E                   "readOnly": true,
E                   "description": "The date-time the user was enrolled in the Narmi system.",
E                   "example": "2018-03-26 14:43:59.004000+00:00"
E               }
```
 this used to work in `3.35.3` and I'm wondering how I can continue to allow it to properly validate as a date-time field?

### To Reproduce

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:

1. Set a field in your API response, which is marked in the open api schema as a `date-time` formatted via python `str()` 
2. Run schema through schemathesis

Please include a minimal API schema causing this issue:

```yaml
components:
  schemas:
    Profile:
      type: object
      description: ''
      properties:
        date_joined:
          type: string
          format: date-time
          readOnly: true
          description: The date-time the user was enrolled.
          example: '2018-03-26 14:43:59.004000+00:00'
```

### Expected behavior

Clearly describe your expected outcome.

Dates formatted with `str()` should validate, or there should be a way to allow for their bespoke validation.

### Environment

```
- OS: MacOS (Apple Silicon)
- Python version: 3.9
- Schemathesis version: 3.35.3
- Spec version: 3.0.1
```

### Additional context

Include any other relevant details, like logs or screenshots.
