### ISSUE TITLE
[BUG] Schemathesis stops sending authentication token after several successful requests

### ISSUE THREAD

**Issue by adm2d** [schemathesis/schemathesis#2779]
### Checklist

- [ ] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq.html#frequently-asked-questions) of the documentation
- [ ] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [ ] I am using the latest version of Schemathesis

### Describe the bug
After executing a random number of successful requests, schemathesis executes the request without transmitting the authentication token. This behavior has been observed since version 3.38.6 and higher. Version 3.38.5 always transmits the authentication token and testing completes successfully.

### To Reproduce

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:

1. Run this command 
```ps1
st run -H "Authorization: Bearer cd4164b3-24d5-49a2-988f-c0752852d429" swagger.json --base-url http://192.168.10.132:21108 --include-path /api/v1/partners-group/create --hypothesis-max-examples=10 --checks all
```
3. See error
```ps1
==================================================================== Schemathesis test session starts ===================================================================
Schema location: file:///D:/Projects/API/swagger.json
Base URL: http://192.168.10.132:21108
Specification version: Open API 3.0.1
Random seed: 198840327513483290421300558028870454940
Workers: 1
Collected API operations: 1
Collected API links: 3
API probing: SUCCESS
Schema analysis: SKIP

POST /api/v1/partners-group/create F                                                                                                                               [100%]

================================================================================ FAILURES ===============================================================================
___________________________________________________________________ POST /api/v1/partners-group/create __________________________________________________________________
1. Test Case ID: xHfh8K

- Authentication declared but not enforced for this operation

    The API returned `403 Forbidden` for `POST /api/v1/partners-group/create` that requires authentication.

[403] Forbidden:

    `{"timestamp":"2025-04-03T11:57:10.187+00:00","status":403,"error":"Forbidden","path":"/api/v1/partners-group/create"}`

Reproduce with:

    curl -X POST -H 'Content-Type: application/json' -d '{"name": "000"}' http://192.168.10.132:21108/api/v1/partners-group/create

================================================================================ SUMMARY ================================================================================

Performed checks:
    not_a_server_error                              23 / 23 passed          PASSED
    status_code_conformance                         23 / 23 passed          PASSED
    content_type_conformance                        23 / 23 passed          PASSED
    response_headers_conformance                    23 / 23 passed          PASSED
    response_schema_conformance                     23 / 23 passed          PASSED
    negative_data_rejection                         23 / 23 passed          PASSED
    ignored_auth                                    8 / 23 passed           FAILED

Note: Use the 'X-Schemathesis-TestCaseId' header to correlate test case ids from failure messages with server logs for debugging.

Note: To replicate these test failures, rerun with `--hypothesis-seed=198840327513483290421300558028870454940`

=========================================================================== 1 failed in 2.73s ===========================================================================
```

Please include a minimal API schema causing this issue:

```yaml
{
    "openapi": "3.0.1",    
    "security": [
        {
            "bearer-jwt": [
                "read",
                "write"
            ]
        }
    ],
    "paths": {
        "/api/v1/partners-group/create": {
            "post": {
                "tags": [
                    "Группы контрагентов"
                ],
                "summary": "Создание новой группы",
                "operationId": "createNewGroup",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PartnersGroupDTO"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/PartnersGroupDTO"
                                }
                            }
                        },
                        "links": {
                            "UpdateGroupWithId": {
                                "operationId": "updateGroupInfo",
                                "requestBody": {
                                    "id": "$response.body#/id",
                                    "name": "test",
                                    "extCode": "test",
                                    "comment": "test"
                                }
                            },
                            "GetGroupById": {
                                "operationId": "getGroupById",
                                "parameters": {
                                    "id": "$response.body#/id"
                                }
                            },
                            "DelGroupById": {
                                "operationId": "deleteGroup",
                                "parameters": {
                                    "partnersGroupId": "$response.body#/id",
                                    "checkBefore": false
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/PartnersGroupDTO"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Error",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/PartnersGroupDTO"
                                }
                            }
                        }
                    }
                }
            }
        },
    "components": {
        "schemas": {
            "PartnersGroupDTO": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "description": "Id записи",
                        "format": "uuid",
                        "readOnly": "true"
                    },
                    "name": {
                        "maxLength": 100,
                        "minLength": 3,
                        "type": "string",
                        "description": "Наименование группы контрагентов"
                    },
                    "extCode": {
                        "maxLength": 15,
                        "minLength": 0,
                        "type": "string",
                        "description": "Внешний код"
                    },
                    "comment": {
                        "maxLength": 500,
                        "minLength": 0,
                        "type": "string",
                        "description": "Комментарий"
                    }
                }
            },
```

### Expected behavior
I want the authentication token to always be transmitted, as on version 3.38.5:
```ps1
st run -H "Authorization: Bearer cd4164b3-24d5-49a2-988f-c0752852d429" swagger.json --base-url http://192.168.10.132:21108 --include-path /api/v1/partners-group/create --hypothesis-max-examples=10 --generation-codec=ascii --generation-allow-x00=false --checks all
==================================================================== Schemathesis test session starts ===================================================================
Schema location: file:///D:/Projects/API/swagger.json
Base URL: http://192.168.10.132:21108
Specification version: Open API 3.0.1
Random seed: 125250563246473100078991917351317455173
Workers: 1
Collected API operations: 1
Collected API links: 3
API probing: SUCCESS
Schema analysis: SKIP

POST /api/v1/partners-group/create .                                                                                                                               [100%]

================================================================================ SUMMARY ================================================================================

Performed checks:
    not_a_server_error                              10 / 10 passed          PASSED
    status_code_conformance                         10 / 10 passed          PASSED
    content_type_conformance                        10 / 10 passed          PASSED
    response_headers_conformance                    10 / 10 passed          PASSED
    response_schema_conformance                     10 / 10 passed          PASSED
    negative_data_rejection                         10 / 10 passed          PASSED
    ignored_auth                                    10 / 10 passed          PASSED

Tip: Use the `--report` CLI option to visualize test results via Schemathesis.io.
We run additional conformance checks on reports from public repos.

=========================================================================== 1 passed in 1.12s ===========================================================================
```

### Environment

```
- OS: Windows
- Python version: 3.12.7
- Schemathesis version: 3.39.14
- Spec version: Open API 3.0.1
```

### Additional context

Include any other relevant details, like logs or screenshots.
