### ISSUE TITLE
[BUG] False positive for "Accepted negative data"

### ISSUE THREAD

**Issue by nicolaasuni** [schemathesis/schemathesis#2900]
### Checklist

- [x] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq/) of the documentation
- [x] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [x] I am using the latest version of Schemathesis

### Describe the bug

After upgrading to the new schemathesis 4.0.1 I was getting new errors related to negative and positive data.
I adjusted the code and the openapi spec to handle those cases but there is one that seems a false positive bug.

The project https://github.com/tecnickcom/rndpwd/ schemathesis fails with the following error:

```
GET /password 
 1. Test Case ID: 70oXOM

- Accepted negative data

    Allowed statuses: 400, 401, 403, 404, 406, 422, 428, 5xx

[200] OK:

    `["lnlnlnlulnnlllln","ulnnluunlnlnlnun"]`

Reproduce with: 

    curl -X GET 'http://rndpwd:8071/password?charset=null&length=16&quantity=2'
```

The full log can be seen at:
- https://github.com/tecnickcom/rndpwd/actions/runs/15654012089/job/44102604584

The `charset=null` is a valid input and the output is as expected.
However, schemathesis treats this case as negative data.
The same issue has been observed with other testing strings like `false`.

### To Reproduce

🚨 **Mandatory** 🚨: Steps to reproduce the behavior:

Clone the  https://github.com/tecnickcom/rndpwd/ project and run `make x`.

Schemathesis is running with the following parameters:

```
schemathesis run \
	--checks=all \
	--request-timeout=2000 \
	--max-examples=100 \
	--url='${API_TEST_URL}' \
	${OPENAPI_FILE}
```

Please include a minimal API schema causing this issue:

- https://github.com/tecnickcom/rndpwd/blob/main/openapi.yaml

### Expected behavior

Pass when the string is `null` or `false` if the parameter accepts arbitrary strings.

### Environment

```
- OS: Linux
- Schemathesis version: 4.0.1
- Spec version: Open API 3.0.3
```

**Comment by nicolaasuni** [comment]
NOTE:
I have now added the schemathesis cli runtime option `--exclude-checks=negative_data_rejection` to disable this check to unblock the pipeline.

**Comment by Stranger6667** [comment]
Thank you, @nicolaasuni, for opening this issue and providing so many details!

The core problem is that the generated data is of a different type before it is sent over the wire, and then serialized to a string anyway. Therefore, it is still a string from the backend point of view, even if it is `null` or `false` or `[1, 2, 3]`.

Such test cases can be generated in the negative testing mode, so this should be adjusted. I'll take a look at it soon

**Comment by dimitarkovachev** [comment]
I am also getting such false positive negative_data_rejection test cases, where schemathesis treats valid data as negative:

```yaml
      - description: Page number (1-based)
        in: query
        name: page
        schema:
          default: 1
          minimum: 1
          maximum: 4294967295
          format: uint32
          type: integer
      - description: Number of items per page
        in: query
        name: limit
        schema:
          default: 50
          minimum: 1
          maximum: 50
          format: uint32
          type: integer
``` 

```
- Accepted negative data

    Allowed statuses: 400, 401, 403, 404, 406, 422, 428, 5xx

[200] OK:

    `{"data":[{ // Output truncated...`

Reproduce with:

    curl -X GET -H 'Authorization: [Filtered]' 'http://localhost:8080/api/v1/txs/all?page=4'
```

Also treats missing optional query params as negative negative_data_rejection, expecting error status omitting the optional query param.
