### ISSUE TITLE
[BUG] Schemathesis generates invalid uuid v4

### ISSUE THREAD

**Issue by hdr1210** [schemathesis/schemathesis#2909]
### Checklist

- [ x ] I checked the [FAQ section](https://schemathesis.readthedocs.io/en/stable/faq/) of the documentation
- [ x ] I looked for similar issues in the [issue tracker](https://github.com/schemathesis/schemathesis/issues)
- [ x ] I am using the latest version of Schemathesis

### Describe the bug

UUID v4 generated by schemathesis:
```
"uuid": "e3e70682-c209-4cac-629f-6fbed82c07cd"
```

The generated UUID v4 is invalid. In the fourth segment the first char has to be a one of the following values:
8, 9, A, B, C or D.

Apart from that, I wonder why a UUID is generated at all, since the format is uuidv4.

OpenAPI Spec:

```yaml
article:
        type: object
      properties:
        id:
          type: string
          pattern: "[1-9]+"
          readOnly: true
          example: "1000"
        uuid:
          type: string
          format: uuidv4
          example: "87e28f09-05f8-4f27-b39b-abf2e2f4f220"
```

### Expected behavior

Schemathesis generates an valid uuid v4 address

### Environment

```
- OS: Gitlab CI/CD Python@latest images (debian bookworm)
- Python version: 3.14
- Schemathesis version: 4.0.2
- Spec version: 3.0.3
```

**Comment by Stranger6667** [comment]
What command did you use, and does this value appear consistently among different runs?

My current assumption is that it comes from the constants collected by Hypothesis from the source files - otherwise, locally I can't reproduce it; values are just random strings.

Also, I noted that "e3e70682-c209-4cac-629f-6fbed82c07cd" appears on GH quite often - any chance that you have a schemathesis extension that may depend on packages with that value in their sources? grepping my local dependencies didn't find anything like that

**Comment by hdr1210** [comment]
This error does not appear consistently.

This is the command I use with this config file:

```bash
schemathesis run /tmp/openapi.yaml --exclude-deprecated
```

```toml
base-url = "http://localhost:4000" 

headers = { Authorization = "${API_KEY}" }

continue-on-failure = true

[generation]
max-examples = 10

[checks]
not_a_server_error.enabled = false

[reports]
directory = "test-results"

[phases.coverage]
enabled = false
```
I don't use any extensions for schemathesis.
I use the schemathesis installation provided through pip:
```bash
python -m pip install schemathesis --quiet
```
