### ISSUE TITLE
Run RST syntax check as a part of CI & pre-commit

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#734]
To avoid wrong syntax usage in changelog and docs (and fixes like this one - https://github.com/schemathesis/schemathesis/commit/90a561bf59c0159dd45769233a7d7fef5e6cebe2) 

**Implementation notes**

This project should fit - https://github.com/myint/rstcheck . It supports using as a pre-commit check:

```
  - repo: https://github.com/myint/rstcheck
    rev: ''
    hooks:
      - id: rstcheck
        additional_dependencies:
          - sphinx==3.1.2
```

Note: You have to fix all found errors (not sure how hard it could be with, e.g., syntax errors in code samples, probably their type can be changed to plain text).
