### ISSUE TITLE
[FEATURE] A way to force spec version

### ISSUE THREAD

**Issue by Stranger6667** [schemathesis/schemathesis#876]
Some apps have non-compliant specs, that include e.g.:

```yaml
{
  "swagger": "3.0", 
  "openapi": "3.0.0", 
}
```

Maybe we can force Schemathesis to choose the right spec
