### ISSUE TITLE
[BUG] Producing examples with SyntaxError.

### ISSUE THREAD

**Issue by vlade11115** [schemathesis/schemathesis#885]
**Describe the bug**

Schemathesis generating invalid JSON payload and producing SyntaxError.
```python
requests.put('HOST/transactions/V%C3%8E%7C%C2%81b6%C3%81%F0%BB%9B%A0%F2%84%AA%96%C3%85%05%C3%B0%5C/collections/1%C3%99%11X%C2%8D', headers={'x-api-key': 'KEY', 'User-Agent': 'schemathesis/2.8.0'}, json={'data': {'!ù\x05': [{'A\U000b5b33À`\x99\uf555ü\x02': '\x94', 'Ø\U0009648b\x89è\x92\x9c\x80': {}, '\x1fÏüÞ\x80_\tÒõì': []}, {}], 'Ë\x93': 2.637258487788318e+43, '': [{}, [[None], True, [-9007199254740992.0]], {}], '\U0003ff6b5\U00109318ã\x1f\uf68f': [[]], 'ì\x1a\x9a': {}, '\U0006e270í¤Ü\U00104b40§ÍÈ𘚿\U00071eacPB9k\U000a2c16': {'\U00102941dü1\U0009e7b1!\U000434bc\x08\r\U000f5c7c\U000aed63\U00035d6a\U000f9359': -78, 'Y\U0003b158©\x7f#\tâ\U000970af\U00074f1c': {}}, '\x9b\x9eÿ': {}, 'õÒè<\x05Ö2B¤v\U00065c6eù¤\U00104e66\U000ced18%\xa0"dw\x17ª\x92ÏR\U00074d07\U000a5eed': {'Çñ¼¶þë´\x87': {}, '': -16687}, 'Z\x87\x8c]5\x0fyR\x86\U001081cb𬑢ã\U000e478f&': [{}, {}], '\x00\x87jzI ': [False, [] {'': None, 'ç': 0.0}], '\x93<': {'\n\uf00d': [{'¥醆§Þ\x13³\U0008df5d\U000628e9êÔ': -1.5, '\x935Áé\U0004c8ad§#|': '\x9b|¯[\x9c\U0003b32dB\x07«', '06\x9e*\U0002fd6d\U000bef91¿·Ý)©ù': -24940}], 'íZ\000f7c8a\x95\U0004715f\x8d+-': {}, 'íT)¬': -6.997965566385589e+16}}, '\U00092506\U000d42a5¸µ*\U0007446b]': {'õñ\x1c>x¼\U000f43b8': False, '\U00083dee': {}, 'l\U00057240\U000b80f9': {'ÌO\x11': [None, '\x85', -2.854204201425003e+203]}}, 'metadata': {'ôW\U0009287d\U000b3e18\x17\x02ÑDO\U0001e216)æ': [[None, [False]]]}})
```
[Link to visual representation.](https://imgur.com/a/3LaIiKG)

HOST and KEY are removed by me because it's containing sensitive data.

**To Reproduce**
I am not sure how we can reproduce this, due to the random nature of tests. When it happens again, I will try to capture more detailed info and probably sid.

If possible, please post a minimal version of your API schema that cause this behavior:

```yaml
    Collection:
      title: Collection
      description: Collection is set of datapoints, connected to transaction
      type: object
      properties:
        transaction_id:
          type: string
          format: uuid
          description: "Transaction id"
          example: "6b19feeb-7433-448e-b285-b758d19a4fe6"
        collection_id:
          type: string
          format: uuid
          description: "Collection id"
          example: "8109c79a-e50b-46b8-8032-0d6e556dfaa0"
        data:
          type: object
          description: Data in  language schema
          additionalProperties: true
        metadata:
          type: object
          description: Metadata about collection, f.e version of used  shema
```

**Expected behavior**
I expect syntax-correct examples generated by schemathesis.

**Environment (please complete the following information):**
 - OS: Mac OS
 - Python version: 3.8.5
 - Schemathesis version: 2.8.0
